//===- KTDPDialect.h - KTDP dialect public header ----------*- C++ -*-===//
//
//===----------------------------------------------------------------------===//
#ifndef KTIR_DIALECT_KTDP_KTDPDIALECT_H_
#define KTIR_DIALECT_KTDP_KTDPDIALECT_H_

#include "mlir/IR/Dialect.h"

// Generated by mlir-tblgen --gen-dialect-decls -dialect=ktdp
#include "ktir/Dialect/KTDP/KTDPDialect.hpp.inc"

#endif // KTIR_DIALECT_KTDP_KTDPDIALECT_H_
